# Generated by Django 4.2.7 on 2026-03-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkstat',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
    ]
