# Generated by Django 4.2.7 on 2026-03-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False, 'ordering': ['-last_seen'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
